### ISSUE TITLE
some functions are not working

### ISSUE THREAD

**Issue by muhme** [joomla-projects/joomla-cypress#9]
I will use this great work to test my Joomla module, but not all used functions work out-of-the-box in Cypress. I saw problems with:
- installJoomlaMultilingualSite()
- installLanguage()
- installExtensionFromFolder()
- displayModuleOnAllPages()
- setModulePosition()
- publishModule()

Since I have fixed these problems, this issue is the preparation for a pull request. With a commit for each function with error description and explanation of my fix. I will test with Joomla 4.3.4 and 5.0.rc3 Along the way I will also expand the documentation a bit. is there anything else to consider?

**Comment by HLeithner** [comment]
I really appreciate your engagement, fixing this functions is really needed the current 0.18  is broken since my last merge.

5.0.0 will be released on Tuesday. So you can wait or use rc2 or last commit in the cms repo it's more or less the same.

Adding documentation would be great, adding it to  manual.joomla.org would be the way to go.

Are you on matter most?

**Comment by muhme** [comment]
i am so free and close the issue now myself, the pull request has long been merged and now it has moved from the dev to the main branch
